### ISSUE TITLE
least useful alias provided

### ISSUE THREAD

**Issue by AdrienLemaire** [molovo/tipz#8]
Using the plugin [oh-my-zsh/git](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git) and tipz from zgen, I notice that the alias suggested by Tipz is not the one I'm expecting. Eg:

```
$ git commit -am "add README" 
'Tipz:' g commit -am "add README"
[master 73cc76a] add README
 1 file changed, 11 insertions(+)
 create mode 100644 tree/README.md
```
I would have preferred Tipz to tell me about "gcam". 

A simple solution would be to go over all aliases available, then return the shortest one ("g commit -am" is 12 chars, "gcam" is only 4, return the later). Is that something you could easily implement ?

Thank you!

**Comment by molovo** [comment]
@Fandekasp what version of tipz are you using? That issue did pop up in 0.1.1 but was fixed in 0.2.0. If you're already using the latest version I'll try and reproduce the issue tomorrow

**Comment by AdrienLemaire** [comment]
Hi @molovo . With a `zgen load molovo/tipz`, zgen downloads the master branch from github. Verified with a diff, I'm using the latest version.

Thank you for the support!

**Comment by molovo** [comment]
@Fandekasp thanks for checking. I'll have a look into it today then. Hopefully it should be an easy fix.

**Comment by molovo** [comment]
@Fandekasp just had a look at the oh-my-zsh git plugin. If you look at https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L68 you'll see that the alias is defined there as `git commit -a -m` rather than the `git commit -am` you were entering. Unfortunately there's no way for Tipz to know that they are equivalent, as I can only search the exact text entered in the alias definition. If you were to run `git commit -a -m "add README"` rather than `git commit -am "add README"` you should see the Tipz prompt correctly.

**Comment by AdrienLemaire** [comment]
oh... right. Got it, I'll keep that in mind. Thank you @molovo !
